### ISSUE TITLE
Max height is not set on images in Dashboard page

### ISSUE THREAD

**Issue by SarathSantoshDamaraju** [calummoore/webframe#1]
## Issue: 
Unlike landing list screen, Max height is not set to images on dashboard resulting long thumbnails. Since it already has a popup with full width image, is it necessary to show the full width image in dashboard as well?

## How to replicate:
1. After logging-in, **Save** any long image
2. Go to your **Dashboard** and you will see the issue. 

## References:
List page:
![Group 1](https://user-images.githubusercontent.com/10527102/58611941-7e93cc80-82ce-11e9-9286-5b7f72e457de.png)

 ---

Dashboard page:
![Group 2](https://user-images.githubusercontent.com/10527102/58611953-86537100-82ce-11e9-998d-b5701a91f5b3.png)

And if you agree this has to be fixed, can I work on it.

**Comment by calummoore** [comment]
Hi @SarathSantoshDamaraju, thanks for raising the issue! I really appreciate your feedback.

It was a fairly quick fix, so I've gone in and made the change - feel free to raise another issue if you spot something else! 🙂
